import type { ModuleDefinition } from "./onboard-types";

export const MODULES: ModuleDefinition[] = [
  {
    id: "inventory",
    name: "Inventory Management",
    shortDescription: "Track products, services, categories, vendors, and stock levels in real time.",
    fullDescription:
      "Your centralized hub for managing everything you sell. Add products and services, organize them into categories and subcategories, set up vendor relationships for easy reordering, track stock levels with alerts, and manage equipment, damaged goods, and testers. Real-time sync keeps your inventory accurate across all channels.",
    icon: "Package",
    phase: 1,
    prerequisites: [],
    setupSteps: [
      {
        id: "inv-1",
        title: "Add your first product or service",
        description: "Create at least one inventory item with name, price, and SKU.",
        completed: false,
      },
      {
        id: "inv-2",
        title: "Create a category",
        description: "Organize your items by creating categories like 'Food', 'Beverages', or 'Services'.",
        completed: false,
      },
      {
        id: "inv-3",
        title: "Set up a vendor",
        description: "Add a vendor so you can track purchases and reorder stock easily.",
        completed: false,
      },
      {
        id: "inv-4",
        title: "Configure inventory alerts",
        description: "Set minimum and maximum stock levels to get notified when items run low or overstock.",
        completed: false,
      },
      {
        id: "inv-5",
        title: "Review inventory dashboard",
        description: "Check your stock-in-hand report and inventory logs to ensure everything is set up correctly.",
        completed: false,
      },
    ],
    features: [
      "Real-time stock tracking across all channels",
      "Product and service management with images, SKUs, and pricing",
      "Category and subcategory organization",
      "Vendor management and purchase order reordering",
      "Low/high stock alerts via email and SMS",
      "Equipment, damaged goods, and tester tracking",
      "Barcode and QR code generation",
      "Inventory count with employee accountability",
      "Stock adjustment with audit trail",
      "Sale price scheduling with date ranges",
    ],
    whyItMatters: {
      retail: "As a retail business, accurate inventory is the backbone of your operations. Avoid stockouts and overstock situations.",
      restaurant: "Track ingredients, supplies, and menu items. Know exactly what you have and when to reorder.",
      salon: "Manage your product inventory alongside services. Track retail products and professional supplies separately.",
      health: "Keep supplements, equipment, and retail items organized with automatic low-stock alerts.",
      professional: "Even service businesses benefit from tracking materials, supplies, and billable items.",
      ecommerce: "Real-time inventory sync prevents overselling across your online channels.",
      hospitality: "Track room supplies, amenities, and retail items with automatic reorder points.",
      other: "Every business needs to know what they have, what they need, and what's selling.",
      default: "Accurate inventory management is the foundation of a well-run business.",
    },
  },
  {
    id: "crm",
    name: "CRM & Customers",
    shortDescription: "Manage leads, prospects, and customers with a complete relationship pipeline.",
    fullDescription:
      "Build and nurture your customer relationships from first contact to loyal advocate. Track leads through your sales funnel, convert prospects into customers, manage contact details, segment customers into groups, schedule appointments, and maintain detailed communication history. Import existing customer lists via CSV for quick setup.",
    icon: "Users",
    phase: 1,
    prerequisites: [],
    setupSteps: [
      {
        id: "crm-1",
        title: "Add your first customer",
        description: "Create a customer profile with name, email, and phone number.",
        completed: false,
      },
      {
        id: "crm-2",
        title: "Set up lead statuses",
        description: "Define stages like 'New', 'Contacted', 'Qualified', 'Won' to track your sales pipeline.",
        completed: false,
      },
      {
        id: "crm-3",
        title: "Create a customer segment",
        description: "Group customers by criteria like spending level, location, or purchase frequency.",
        completed: false,
      },
      {
        id: "crm-4",
        title: "Import existing customers",
        description: "Upload a CSV file to bring your existing customer list into the system.",
        completed: false,
      },
      {
        id: "crm-5",
        title: "Configure prospect settings",
        description: "Set follow-up duration and notification preferences for new leads.",
        completed: false,
      },
    ],
    features: [
      "Lead, prospect, and customer management pipeline",
      "Customer segmentation and group targeting",
      "Appointment scheduling and calendar sync",
      "Communication history (email, SMS, calls, notes)",
      "CSV import for bulk customer upload",
      "Lead source and funnel tracking",
      "Customer reward points management",
      "Deactivation and reactivation controls",
      "Employee assignment to customers",
      "Detailed customer analytics and order history",
    ],
    whyItMatters: {
      retail: "Know your customers by name. Track purchase history to offer personalized recommendations.",
      restaurant: "Build a loyal customer base with targeted outreach and reservation management.",
      salon: "Track client preferences, appointment history, and communication for a personal touch.",
      health: "Manage patient/client records, appointment scheduling, and follow-up communications.",
      professional: "Nurture leads through your sales pipeline and maintain detailed client records.",
      ecommerce: "Understand online shoppers, segment by behavior, and drive repeat purchases.",
      hospitality: "Track guest preferences and history for a premium, personalized experience.",
      other: "Understanding your customers is the key to growing any business.",
      default: "A strong CRM turns one-time buyers into lifelong customers.",
    },
  },
  {
    id: "employees",
    name: "Employee Management",
    shortDescription: "Manage your team with scheduling, clock in/out, payroll, and role-based access.",
    fullDescription:
      "Everything you need to run your team efficiently. Add employees with detailed profiles, assign roles and access permissions, track clock in/out times, generate payroll reports, set up working hours and schedules, manage commissions, and enable team communication via built-in messenger. Includes file cabinet for document sharing and e-learning for training.",
    icon: "UserCog",
    phase: 1,
    prerequisites: [],
    setupSteps: [
      {
        id: "emp-1",
        title: "Add your first employee",
        description: "Create an employee profile with name, contact info, role, and working hours.",
        completed: false,
      },
      {
        id: "emp-2",
        title: "Set up roles and permissions",
        description: "Define what each employee can view, create, edit, and delete in the system.",
        completed: false,
      },
      {
        id: "emp-3",
        title: "Configure working hours",
        description: "Set the days and times each employee works, including timezone.",
        completed: false,
      },
      {
        id: "emp-4",
        title: "Enable clock in/out",
        description: "Allow employees to track their time and generate hours-worked reports.",
        completed: false,
      },
      {
        id: "emp-5",
        title: "Set up commission structure",
        description: "Define daily, weekly, or monthly commission percentages for your team.",
        completed: false,
      },
    ],
    features: [
      "Employee profiles with detailed information",
      "Role-based access control and authorization",
      "Clock in/out time tracking",
      "Payroll reports with wages and commissions",
      "Volume and order commission management",
      "Availability scheduling for appointments",
      "Built-in team messenger",
      "File cabinet for document sharing",
      "E-learning forms for training",
      "Employee import via CSV",
    ],
    whyItMatters: {
      retail: "Schedule shifts, track hours, and manage commissions for your sales team.",
      restaurant: "Manage kitchen and floor staff with shift scheduling and time tracking.",
      salon: "Assign stylists to clients, track hours, and manage service commissions.",
      health: "Schedule practitioners, track certifications, and manage appointments.",
      professional: "Control access levels, track billable hours, and manage team assignments.",
      ecommerce: "Manage warehouse and fulfillment staff with role-based system access.",
      hospitality: "Coordinate front desk, housekeeping, and service staff schedules.",
      other: "Efficient team management saves time and reduces operational overhead.",
      default: "Keep your team organized, accountable, and motivated.",
    },
  },
  {
    id: "fastshop",
    name: "Fast Shop (E-Commerce)",
    shortDescription: "Launch your online store with themes, categories, and built-in payment processing.",
    fullDescription:
      "Your all-in-one platform to sell your entire inventory online. Choose from beautiful themes, upload banners and logos, organize products into categories, manage orders, connect your domain, and even sell on Google Shopping. Fast Shop syncs with your inventory in real time so your online and in-store stock stay identical.",
    icon: "ShoppingCart",
    phase: 2,
    prerequisites: ["inventory"],
    setupSteps: [
      {
        id: "fs-1",
        title: "Add at least 3 products to inventory",
        description: "Your online store needs products to display. Add them in Inventory Management first.",
        prerequisiteModuleId: "inventory",
        completed: false,
      },
      {
        id: "fs-2",
        title: "Choose a store theme",
        description: "Select from available themes to match your brand's look and feel.",
        completed: false,
      },
      {
        id: "fs-3",
        title: "Upload your logo and banner",
        description: "Add your brand's logo and a hero banner to personalize your store.",
        completed: false,
      },
      {
        id: "fs-4",
        title: "Set up product categories",
        description: "Organize your products so customers can browse easily.",
        completed: false,
      },
      {
        id: "fs-5",
        title: "Configure shipping and payments",
        description: "Set delivery methods, shipping rates, and payment gateway.",
        completed: false,
      },
      {
        id: "fs-6",
        title: "Preview and launch your store",
        description: "Review how your store looks and go live when you're ready.",
        completed: false,
      },
    ],
    features: [
      "Beautiful, customizable store themes",
      "Real-time inventory sync with POS",
      "Category and subcategory organization",
      "Custom domain connection",
      "Sell on Google Shopping integration",
      "Google Analytics connection",
      "Order management and fulfillment",
      "Customer list from online orders",
      "Marketing campaigns for store customers",
      "Theme color and banner customization",
    ],
    whyItMatters: {
      retail: "Extend your physical store online. Sell to customers 24/7 without additional overhead.",
      restaurant: "Accept online orders for pickup or delivery with a branded ordering page.",
      salon: "Sell retail products online while keeping your in-store inventory synced.",
      health: "Offer supplements, equipment, and wellness products through your online shop.",
      professional: "Sell digital products, courses, or service packages online.",
      ecommerce: "This is your primary sales channel. A beautiful, fast-loading store drives conversions.",
      hospitality: "Sell gift cards, packages, and merchandise through your branded online store.",
      other: "An online store opens your business to customers around the clock, around the world.",
      default: "Take your business online and reach customers wherever they are.",
    },
  },
  {
    id: "invoices",
    name: "Invoices & Payments",
    shortDescription: "Create invoices, process payments, and manage billing with a virtual terminal.",
    fullDescription:
      "Handle all your billing needs in one place. Create single or recurring invoices, send them via email, process card payments through the virtual terminal, manage estimates, set up payment catchers for your website, handle refunds, and track scheduled transactions. Includes a bill pay portal for customers to pay their outstanding balances.",
    icon: "Receipt",
    phase: 2,
    prerequisites: ["crm"],
    setupSteps: [
      {
        id: "inv-pay-1",
        title: "Add at least 1 customer",
        description: "You need a customer to send invoices to. Set them up in CRM first.",
        prerequisiteModuleId: "crm",
        completed: false,
      },
      {
        id: "inv-pay-2",
        title: "Configure payment gateway",
        description: "Set up Payeezy, Authorize.Net, or CSG Forte to process card payments.",
        completed: false,
      },
      {
        id: "inv-pay-3",
        title: "Create your first invoice",
        description: "Select a customer, add line items, set terms, and send the invoice.",
        completed: false,
      },
      {
        id: "inv-pay-4",
        title: "Process a test payment",
        description: "Use the Virtual Terminal to process a card payment and verify your setup.",
        completed: false,
      },
      {
        id: "inv-pay-5",
        title: "Set up invoice reminders",
        description: "Configure automatic reminders for overdue invoices to reduce outstanding debt.",
        completed: false,
      },
    ],
    features: [
      "Single and recurring invoice creation",
      "Virtual terminal for card payments",
      "Estimate creation and conversion to invoices",
      "Custom payment catchers for websites",
      "Refund processing",
      "Pre-authorized card holds",
      "Recurring sales and subscriptions",
      "Scheduled transaction management",
      "Bill pay portal for customer self-service",
      "Event ticketing with payment collection",
    ],
    whyItMatters: {
      retail: "Speed up checkout and manage customer accounts with flexible billing options.",
      restaurant: "Handle catering invoices, recurring orders, and event billing with ease.",
      salon: "Bill for services, packages, and products with professional invoices sent automatically.",
      health: "Manage patient billing, recurring membership fees, and insurance-related invoicing.",
      professional: "Send professional invoices, track payments, and manage project billing.",
      ecommerce: "Process online payments seamlessly and manage order-based billing.",
      hospitality: "Handle room charges, event billing, and group invoicing efficiently.",
      other: "Get paid faster with professional invoices and flexible payment options.",
      default: "Streamline your billing to improve cash flow and reduce administrative overhead.",
    },
  },
  {
    id: "marketing",
    name: "SMS/Email Marketing",
    shortDescription: "Run coupon campaigns, email blasts, and targeted promotions to grow your business.",
    fullDescription:
      "Reach your customers where they are with powerful email and SMS campaigns. Create coupon codes with flexible discounts, design beautiful email templates (basic, CRM, or enterprise), schedule campaigns for optimal timing, set up recurring sends, and track performance with detailed analytics including open rates, click rates, and revenue attribution.",
    icon: "Megaphone",
    phase: 3,
    prerequisites: ["crm"],
    setupSteps: [
      {
        id: "mkt-1",
        title: "Add customers or customer groups",
        description: "You need recipients for your campaigns. Set them up in CRM first.",
        prerequisiteModuleId: "crm",
        completed: false,
      },
      {
        id: "mkt-2",
        title: "Configure email settings",
        description: "Set up your custom or premium email configuration for sending campaigns.",
        completed: false,
      },
      {
        id: "mkt-3",
        title: "Create your first coupon",
        description: "Set up a discount coupon with a memorable code, amount, and validity period.",
        completed: false,
      },
      {
        id: "mkt-4",
        title: "Launch a campaign",
        description: "Choose a template, write compelling content, select recipients, and send or schedule.",
        completed: false,
      },
      {
        id: "mkt-5",
        title: "Review campaign analytics",
        description: "Check open rates, click rates, and revenue generated from your campaign.",
        completed: false,
      },
    ],
    features: [
      "Coupon creation with flexible discounts",
      "Basic, CRM, and Enterprise email templates",
      "SMS campaign sending",
      "Campaign scheduling and recurring sends",
      "Recipient selection by customer or group",
      "Detailed campaign analytics (opens, clicks, revenue)",
      "Email deliverability tracking",
      "Template preview and customization",
      "Coupon campaign management and cloning",
      "Promotional campaign management (product and store-wide)",
    ],
    whyItMatters: {
      retail: "Drive foot traffic and online sales with targeted promotions and seasonal campaigns.",
      restaurant: "Fill slow nights with special offers and keep regulars coming back with loyalty deals.",
      salon: "Remind clients about appointments, promote new services, and fill empty time slots.",
      health: "Share wellness tips, promote classes, and keep clients engaged between visits.",
      professional: "Nurture leads with valuable content and re-engage past clients with targeted offers.",
      ecommerce: "Recover abandoned carts, announce sales, and drive repeat purchases with email campaigns.",
      hospitality: "Promote special rates, events, and packages to past and potential guests.",
      other: "Marketing campaigns are the most direct way to drive revenue and keep customers engaged.",
      default: "Targeted marketing campaigns directly impact your bottom line.",
    },
  },
  {
    id: "rewards",
    name: "Rewards & Loyalty",
    shortDescription: "Build customer loyalty with points, punch cards, referrals, and birthday rewards.",
    fullDescription:
      "Turn one-time buyers into lifelong fans with a comprehensive loyalty program. Offer first-time purchase rewards, comeback incentives, birthday treats, punch card programs, and referral bonuses. Track reward redemption, set up multi-merchant connections, customize reward flyers, and promote your programs across email, SMS, and social media.",
    icon: "Gift",
    phase: 3,
    prerequisites: ["crm"],
    setupSteps: [
      {
        id: "rwd-1",
        title: "Set up your customer base",
        description: "You need customers enrolled to award and redeem points. Set them up in CRM first.",
        prerequisiteModuleId: "crm",
        completed: false,
      },
      {
        id: "rwd-2",
        title: "Configure reward points settings",
        description: "Set the points-to-dollar ratio, earning rules, and expiration period.",
        completed: false,
      },
      {
        id: "rwd-3",
        title: "Activate first-time rewards",
        description: "Set welcome points for new customers and configure validity period.",
        completed: false,
      },
      {
        id: "rwd-4",
        title: "Set up a punch card program",
        description: "Define how many purchases earn a free product or gift card.",
        completed: false,
      },
      {
        id: "rwd-5",
        title: "Promote your rewards program",
        description: "Share your rewards via email, SMS, or social media to drive enrollment.",
        completed: false,
      },
    ],
    features: [
      "First-time purchase reward points",
      "Comeback rewards for lapsed customers",
      "Birthday reward automation",
      "Punch card loyalty programs",
      "Refer-a-friend reward system",
      "Multi-merchant reward connections",
      "Customizable reward flyer templates",
      "Reward redemption time slot management",
      "Reward reminder automation",
      "Comprehensive rewards dashboard and analytics",
    ],
    whyItMatters: {
      retail: "Loyal customers spend 67% more than new ones. A rewards program keeps them coming back.",
      restaurant: "Punch cards and birthday rewards drive repeat visits and increase average order value.",
      salon: "Reward loyal clients and incentivize referrals to grow your client base organically.",
      health: "Encourage regular visits with loyalty points and reward consistent commitment.",
      professional: "Referral rewards turn satisfied clients into your best marketing channel.",
      ecommerce: "Loyalty programs increase customer lifetime value and reduce acquisition costs.",
      hospitality: "VIP rewards create memorable experiences and drive direct bookings.",
      other: "A loyalty program is one of the most cost-effective ways to increase revenue.",
      default: "Retaining existing customers costs 5x less than acquiring new ones.",
    },
  },
  {
    id: "analytics",
    name: "Analytics & Reporting",
    shortDescription: "Understand your business with order, inventory, campaign, and customer analytics.",
    fullDescription:
      "Make data-driven decisions with comprehensive analytics across every aspect of your business. Track order volume and revenue, analyze inventory performance and profitability, measure campaign effectiveness, understand customer segments and behavior, visualize sales by geography, and monitor shipping and payment distributions. Export reports for offline analysis.",
    icon: "BarChart3",
    phase: 4,
    prerequisites: [],
    setupSteps: [
      {
        id: "anl-1",
        title: "Explore order analytics",
        description: "View key metrics like order count, revenue, and average order value over time.",
        completed: false,
      },
      {
        id: "anl-2",
        title: "Review inventory analytics",
        description: "Check top products, stock value, potential revenue, and margin reports.",
        completed: false,
      },
      {
        id: "anl-3",
        title: "Check campaign analytics",
        description: "Measure email open rates, click-through rates, and revenue attribution.",
        completed: false,
      },
      {
        id: "anl-4",
        title: "Explore CRM analytics",
        description: "Understand customer segments, spending patterns, and acquisition trends.",
        completed: false,
      },
      {
        id: "anl-5",
        title: "Download your first report",
        description: "Export a report in PDF or Excel format for offline review or sharing.",
        completed: false,
      },
    ],
    features: [
      "Order analytics with revenue, AOV, and trends",
      "New vs. repeat customer analysis",
      "Sales by geography (interactive map)",
      "Inventory valuation and margin reports",
      "Top and weakest product identification",
      "Campaign performance tracking",
      "Email deliverability analytics",
      "Customer segment analytics",
      "Shipping and payment distribution charts",
      "Exportable reports (PDF/Excel)",
    ],
    whyItMatters: {
      retail: "Know your best sellers, busiest times, and most profitable customers at a glance.",
      restaurant: "Track menu performance, peak hours, and customer spending patterns.",
      salon: "Understand which services drive revenue and which clients are most valuable.",
      health: "Monitor client retention, class attendance, and revenue trends over time.",
      professional: "Track project profitability, client acquisition costs, and revenue forecasts.",
      ecommerce: "Analyze conversion funnels, customer lifetime value, and marketing ROI.",
      hospitality: "Monitor occupancy trends, revenue per guest, and seasonal patterns.",
      other: "Data-driven decisions consistently outperform gut feelings.",
      default: "Analytics transform raw data into actionable insights for growth.",
    },
  },
];

export const PHASE_LABELS: Record<number, { name: string; description: string }> = {
  1: { name: "Foundation", description: "Set up the building blocks of your business" },
  2: { name: "Sales Channels", description: "Start selling to your customers" },
  3: { name: "Growth", description: "Expand your reach and build loyalty" },
  4: { name: "Insights", description: "Understand and optimize your performance" },
};

export function getModuleById(id: string): ModuleDefinition | undefined {
  return MODULES.find((m) => m.id === id);
}

export function getModulesByPhase(phase: number): ModuleDefinition[] {
  return MODULES.filter((m) => m.phase === phase);
}
